---
- name: Server role
  hosts: localhost
  connection: local
  become: true
  roles:
    - server
  tags: server

- name: OBS role
  hosts: localhost
  connection: local
  become: true
  roles:
    - obs
  tags: obs
