---
- name: Workstation role
  hosts: localhost
  connection: local
  become: true
  roles:
    - workstation
  tags: workstation

- name: OBS role
  hosts: localhost
  connection: local
  become: true
  roles:
    - obs
  tags: obs