---
# defaults file for workstation
common_packages:
  - curl
  - git
  - gpg-agent
  - htop
  - openssh-client
  - python3
  - python3-pip
  - python3-venv
  - unzip
  - vim
  - wget
  - zsh

debian_pyenv_prereqs:
  - make 
  - build-essential 
  - libssl-dev 
  - zlib1g-dev 
  - libbz2-dev 
  - libreadline-dev 
  - libsqlite3-dev 
  - wget 
  - curl 
  - llvm
  - libncursesw5-dev 
  - xz-utils 
  - tk-dev 
  - libxml2-dev 
  - libxmlsec1-dev 
  - libffi-dev 
  - liblzma-dev

debian_packages:
  - apt-transport-https
  - ca-certificates

user: anthony
chezmoi_config: https://github.com/digitalsoba/dotfiles.git