- name: Check if chezmoi is installed
  command: chezmoi --version
  register: chezmoi_installed
  ignore_errors: yes
  changed_when: false
- name: Check if chezmoi was already initialized
  become: yes
  become_user: "{{ user }}"
  command: chezmoi verify
  register: chezmoi_verify
  ignore_errors: yes
  changed_when: false
- name: Install chezmoi
  shell: sh -c "$(curl -fsLS git.io/chezmoi)"
  when: chezmoi_installed.rc not in [0]
- name: Chezmoi init
  become: yes
  become_user: "{{ user }}"
  command: "chezmoi init {{ chezmoi_config }}"
  when: chezmoi_verify.rc not in [0]
- name: Apply dotfiles
  command: chezmoi apply
  become: yes
  become_user: "{{ user }}"
  when: chezmoi_verify.rc not in [0]
