- name: Make .font firectory
  file:
    path: /home/anthony/.fonts
    state: directory
    mode: 0755

- name: Install MesloLGS NF Regular
  get_url:
    url: https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Regular.ttf
    dest: /home/anthony/.fonts/MesloLGS NF Regular.ttf
    mode: 0755

- name: Install MesloLGS NF Bold
  get_url:
    url: https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold.ttf
    dest: /home/anthony/.fonts/MesloLGS NF Bold.ttf
    mode: 0755

- name: Install MesloLGS NF Italic
  get_url:
    url: https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Italic.ttf
    dest: /home/anthony/.fonts/MesloLGS NF Italic.ttf
    mode: 0755

- name: Install MesloLGS NF Bold Italic
  get_url:
    url: https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold%20Italic.ttf
    dest: /home/anthony/.fonts/MesloLGS NF Bold Italic.ttf
    mode: 0755