---
- name: Debian common
  include_tasks: debian.yml
  when: ansible_os_family == 'Debian' or ansible_os_family == 'Pop!_OS'

- name: Include fonts tasks
  include_tasks: fonts.yml

- name: Include packages tasks
  include_tasks: packages.yml