---
- name: "Debian common"
  include_tasks: debian.yml
  when: ansible_facts['os_family'] == 'Debian'

- name: Install fonts
  include_tasks: fonts.yml

- name: Install common packages
  include_tasks: packages.yml