---
- name: Include User tasks
  include_tasks: user.yml
  when: ansible_os_family == 'Debian' or ansible_os_family == 'Pop!_OS'
- name: Include fonts tasks
  include_tasks: fonts.yml
- name: Include packages tasks
  include_tasks: packages.yml
- name: Include devtools tasks
  include_tasks: devtools.yml
- name: Include k8s tasks
  include_tasks: k8s.yml
- name: Include oh-my-zsh tasks
  include_tasks: oh-my-zsh.yml
- name: Include dotfiles tasks
  include_tasks: dotfiles.yml
