---
- name: Debian common
  include_tasks: debian.yml
  when: ansible_facts['os_family'] == 'Debian'

- name: Include fonts tasks
  include_tasks: fonts.yml

- name: Include packages tasks
  include_tasks: packages.yml