---
- name: Check if .oh-my-zsh exists
  stat:
    path: "/home/{{ user }}/.oh-my-zsh"
  register: oh_my_zsh_exists
- name: Clone oh-my-zsh
  become: yes
  become_user: "{{ user }}"
  git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: "/home/{{ user }}/.oh-my-zsh"
    version: master
    depth: "1"
  when: not oh_my_zsh_exists.stat.exists
- name: Check if starship.rs is installed
  command: starship --version
  register: starship_exists
  ignore_errors: yes
  changed_when: false
- name: Install starship.rs
  shell: sh -c "$(curl -fsSL https://starship.rs/install.sh)" -- -y
  when: starship_exists.rc not in [0]
- name: Install zsh-autosuggestions plugin
  become: yes
  become_user: "{{ user }}"
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: "/home/{{ user }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
    version: master
    depth: "1"