---
- name: Check if .oh-my-zsh exists
  stat:
    path: /home/anthony/.oh-my-zsh
  register: oh_my_zsh_exists

- name: Clone oh-my-zsh
  git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: /home/anthony/.oh-my-zsh
    version: master
  when: not oh_my_zsh_exists.stat.exists

- name: Change user shell to zsh
  user:
    name: anthony
    shell: /usr/bin/zsh