---
- name: Install common apt packages
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: present
  loop: "{{ apt_packages }}"

- name: Check if sudo is present
  group:
    name: sudo
    state: present
