---
- name: Create user and add to sudo
  ansible.builtin.user:
    name: "{{ user }}"
    state: present
    groups: "{{ sudogroup }}"
    shell: /bin/bash
    createhome: yes

- name: Add user to sudoers file
  ansible.builtin.copy:
    dest: "/etc/sudoers.d/{{ user }}"
    content: "{{ user }}  ALL=(ALL)  NOPASSWD:  ALL"
    owner: root
    group: root
    mode: "0440"

- name: Set pubkey for {{ user }}
  ansible.posix.authorized_key:
    user: "{{ user }}"
    state: present
    key: "{{ github_keys_url }}"

- name: Copy sshd config
  ansible.builtin.template:
    dest: /etc/ssh/sshd_config
    src: sshd_config.j2
    owner: root
    group: root
    mode: "0644"
  notify: Restart sshd

- name: Ensure sshd service is running
  ansible.builtin.systemd:
    name: sshd
    state: started
    enabled: yes
