name: Ansible roles test
on:  
  push:
  pull_request:
    branches:
      - main
jobs:
  test-server:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install molecule
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install pip requirements
      run: pip install -r requirements.txt
    - name: Run molecule test
      run: |
        cd roles/server
        molecule test
  test-workstation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install molecule
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install pip requirements
      run: pip install -r requirements.txt
    - name: Run molecule test
      run: |
        cd roles/workstation
        molecule test