name: Ansible roles test
on:  
  pull_request:
    branches:
      - main
jobs:
  test-server:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - rockylinux8
          - debian10
          - ubuntu2204
          - ubuntu2004
    steps:
    - uses: actions/checkout@v3
    - name: Install molecule
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: 'pip'
    - name: Install pip requirements
      run: pip install -r requirements.txt
    - name: Run molecule test
      env:
        PY_COLORS: '1'
        ANSIBLE_FORCE_COLOR: '1'
        MOLECULE_DISTRO: ${{ matrix.distro }}
      run: |
        cd roles/server
        molecule test
  test-workstation:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - ubuntu2204
          - ubuntu2004
    steps:
    - uses: actions/checkout@v3
    - name: Install molecule
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: 'pip'
    - name: Install pip requirements
      run: pip install -r requirements.txt
    - name: Run molecule test
      env:
        PY_COLORS: '1'
        ANSIBLE_FORCE_COLOR: '1'
        MOLECULE_DISTRO: ${{ matrix.distro }}
      run: |
        cd roles/workstation
        molecule test